version: '2.1'

networks:
  evilnet1:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
      -
        subnet: 198.42.12.0/24
  evilnet2:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
      -
        subnet: 198.42.42.0/24

services:
  mallory:
    hostname: mallory
    cap_add:
      - NET_ADMIN
      - NET_RAW
    image: mitm-bzrtp
    stdin_open: true
    tty: true
    entrypoint: /root/start.sh
    networks:
      evilnet1:
        ipv4_address: 198.42.12.254
      evilnet2:
        ipv4_address: 198.42.42.254
  alice:
    hostname: alice
    cap_add:
      - NET_ADMIN
    image: vulnerable-bzrtp
    stdin_open: true
    tty: true
    entrypoint: /root/start.sh alice
    networks:
      evilnet1:
        ipv4_address: 198.42.12.2
  bob:
    hostname: bob
    cap_add:
      - NET_ADMIN
    image: vulnerable-bzrtp
    stdin_open: true
    tty: true
    entrypoint: /root/start.sh bob
    networks:
      evilnet2:
        ipv4_address: 198.42.42.2
